### ISSUE TITLE
Set landing page carousel images and captions getting cut off

### ISSUE THREAD

**Issue by wickr** [OregonDigital/oregondigital#1177]
The carousel images on set landing pages appear to be pushed down more than usual and this is obscuring the captions and bottom of images. Some of the less tall images appear ok, but the initial 'tallest' images and any others of the same size have images.

http://oregondigital.org/sets/ocfrp
- first image has caption blocked off

http://oregondigital.org/sets/finley-bohlman
- images 1, 2 and 4 have issues

http://oregondigital.org/sets/maic
- both images have no captions

If I right-click and Inspect Element on the image, and then disable these:

```css
a img {
    padding-top: 6px;
    padding-bottom: 6px; 
    display: block;
}
```

it gets back pretty close to normal.
